# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bifrost Dev
version: dev-2025-04-21
slug: bifrost-dev
description: "Bifrost enables you to emulate a Philips Hue Bridge to control lights, groups and scenes from Zigbee2Mqtt."
url: "https://github.com/chrivers/bifrost/tree/dev"
arch:
  - amd64
  - aarch64
init: false

## Map config into container (writable)
map:
  - config:rw

## needed to bind to port 80 and 443
privileged:
  - NET_ADMIN

## needed to access the mac address of the physical interface
host_network: true

## enabling this gives +2 bogus security points
#ingress: true

## might be useful when we have a web ui
# panel_icon: lightbulb-group

## apparmor with home assistant does. not. freaking. work.
## too many hours wasted debugging this..
#
# apparmor: true
apparmor: false
