# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bifrost
version: master-2026-01-14-2
slug: bifrost
description: "Bifrost enables you to emulate a Philips Hue Bridge to control lights, groups and scenes from Zigbee2Mqtt."
url: "https://github.com/rafaelborja/homeassistant-bifrost-hassio"
arch:
  - amd64
  - aarch64
init: false

## Map config into container (writable)
map:
  - config:rw

## needed to bind to port 80 and 443
privileged:
  - NET_ADMIN

## needed to access the mac address of the physical interface
host_network: true

## enabling this gives +2 bogus security points
#ingress: true

## might be useful when we have a web ui
# panel_icon: lightbulb-group

## apparmor with home assistant does. not. freaking. work.
## too many hours wasted debugging this..
#
# apparmor: true
apparmor: false

options:
  bridge_mac: ""
  bridge_ip: ""
  mqtt_host: core-mosquitto
  z2m_host: 127.0.0.1
  z2m_port: 1883
  z2m_topic: zigbee2mqtt
  z2m_token: ""
  overwrite_config: false
  debug: false

schema:
  bridge_mac: str?
  bridge_ip: str?
  mqtt_host: str
  z2m_host: str
  z2m_port: int
  z2m_topic: str
  z2m_token: str?
  overwrite_config: bool
  debug: bool
